services:
  web:
    build: .
    container_name: TronAPI
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:17
    container_name: cont_psql
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: